@startuml change-password
hide circle
skinparam classAttributeIconSize 0
title Change Password
class User {
  +userId: UUID
  +email: string
  +username: string
  +passwordHash: string
  +role: Role
  +isBanned: bool
  +displayName: string
  +avatarUrl: string
}

@enduml
