@startuml
hide circle
skinparam classAttributeIconSize 0
title US-36: Pagination
class Game {
  +gameId: UUID
  +title: string
  +price: decimal
  +discountPercent: int
  +status: GameStatus
  +rejectionReason: string
}

@enduml